name: xHomes
version: '1.0'
main: org.fstpdev.Homes
api-version: '1.20'
author: Lewis Pull
description: Advanced homes system with GUI support
commands:
  home:
    description: Open homes GUI
    usage: /home
    aliases: [homes]
    permission: xhomes.home
  sethome:
    description: Set a new home
    usage: /sethome
    permission: xhomes.sethome
  delhome:
    description: Delete a home
    usage: /delhome <number>
    permission: xhomes.delhome

permissions:
  xhomes.home:
    description: Allows access to the homes GUI
    default: true
  xhomes.sethome:
    description: Allows players to set a home
    default: true
  xhomes.delhome:
    description: Allows players to delete a home
    default: true